### ISSUE TITLE
AuthProvider error on loadItem

### ISSUE THREAD

**Issue by Karrthik-Arya** [descope/descope-react-native#11]
I have a simple react native project on which I wanted to integrate descope onboarding flows. However simply wrapping the App in `<AuthProvider />` gives the following error.
```
 ERROR  TypeError: Cannot read property 'loadItem' of null

This error is located at:
    in AuthProvider (created by App)
    in RCTSafeAreaView (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in EventsMeet(RootComponent), js engine: hermes
```
Heres the screenshot from the app:
![Simulator Screenshot - iPhone 15 - 2024-02-14 at 21 43 28](https://github.com/descope/descope-react-native/assets/76391390/f891e455-91d0-41e9-9d67-b54c5e3519b4)

I am using 
React Native: 0.72.6 on iOS 17.2 emulator

**Comment by Karrthik-Arya** [comment]
Any Updates?

**Comment by itaihanski** [comment]
@Karrthik-Arya Thanks for reporting, can please provide a step-by-step guide to recreate that error? How the project was created, exact sequence for initialization commands, code used, etc.

**Comment by iStefo** [comment]
I had the same issue on a blank, brand-new react native project using `react-native@latest init <name>` followed only by the install instructions from this project's readme . (regarding repro @itaihanski)

After some digging, I found out that it's missing the native (iOS/Android) module to import. In my case, it was solved for iOS by navigating to `/ios` and running `pod install` there, which built the `descope-react-native` artefact.

**Comment by itaihanski** [comment]
Thanks @iStefo, I'll make sure to clarify this point in the README.
